### PR TITLE
Mini cart on checkout page

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #225 

Added setting - defaults to false

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Sorry for missing this. I think for this setting, basically, users wanted to have the mini-cart always present. Can we make it present on the Cart page too. My bad for not labelling and explaining this better.

**Comment by adiraomj** [comment]
Updated. Please check @Misplon

**Comment by Misplon** [comment]
Thanks @adiraomj. Can you perhaps check that the cart contents are appearing correctly on hover on the cart and checkout pages?

**Comment by adiraomj** [comment]
The cart widget is not displayed on cart and checkout pages by default. Fixed it. :)

**Pull request merged**
