### PR TITLE
changes for full-accessibility

### PR DESCRIPTION
**Pull request by adiraomj**
Implementing enhancement #6 

A few changes for full accessibility.

I have checked the theme. @Misplon could you please double-check everything and then merge this PR. Let me know if anything has slipped by me.

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Super, thanks dude. I'm going to review this ASAP, just not tonight. We'll include this in the following update and then ping the Accessibility team for a review so we can get the theme tag.

**Comment by Misplon** [comment]
@adiraomj Could you have a look at these conflicts for us? Apologies again for the delays from my side.

**Comment by adiraomj** [comment]
@Misplon I fixed all the merge conflicts. Sorry for the delay.

**Comment by Misplon** [comment]
Thanks dude, checking now. Once we're ready we'll push the next update with the `accessibility-ready` theme tag. That'll trigger a review from that part of the review team. We'll go from there.

**Comment by Misplon** [comment]
@adiraomj thanks dude, here are a few challenges I've noticed. Please, let me know your feedback.

**Header Search Icon**
I can tab through the menu and drop-down items nicely. I can't tab to to the search icon though. Can we look into that?

**Mobile Menu**
The mobile menu will be assessed too. At the moment it doesn't appear possible to open sub-menus using keyboard navigation.

**Comment by Misplon** [comment]
@adiraomj Did you look at contrast? I hope not, but I think we may be stuck. Our button hovers and all secondary text color elements don't meet AA (4:5:1) contract levels. WAVE Chrome extension is the testing tool I'm using.

wave

It doesn't sound like we can have an accessibility setting, we need to be accessible by default to use the theme tag.

**Comment by Misplon** [comment]
@adiraomj It sounds like when icons have accompanying text, the icon should be hidden from screen readers.

_If the icon is supplementing text (e.g., it appears with text that indicates function or purpose), then the icon should not include fallback text, and should be hidden from screen readers using `aria-hidden`._

If I understand this correctly then the following icons should have `aria-hidden` added:

Menu hamburger icon
Next previous post navigation arrows

Can you think of any others?

**Comment by adiraomj** [comment]
I'll look into the header search icon and mobile menu.

I'll add `aria-hidden` to all the icons. 👍

**Comment by Misplon** [comment]
Thanks @adiraomj. Above is all of the feedback/items I can see for now.

**Comment by Misplon** [comment]
@adiraomj When you get a chance, let's see if we can finish up the ideas I had. Then, I'll chat to @gregpriday and see if he still wants to go-ahead with a child theme to complete the list or if we call it a day.

**Comment by Misplon** [comment]
@adiraomj Could you please, take a look at the conflicts when possible. Standing by to check and merge :)

**Pull request merged**
