### PR TITLE
Adjusted smooth scrolling calculations for logo scaling

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #249

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj, [a quick link to our Slack chat](https://siteorigin.slack.com/archives/D0GGJRRM3/p1504706810000771).

You mentioned the issue: happens when the branding text/logo does not have a larger height than the navigation.

Thanks :)

**Comment by adiraomj** [comment]
@Misplon I have made some changes to the calculations. Please test. Thanks.

**Comment by Misplon** [comment]
@adiraomj Please, can you do a quick conflict fix for us. Thanks.

**Comment by adiraomj** [comment]
@Misplon Done.

**Pull request merged**
