### PR TITLE
Sub menu toggle

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #85.

Used the existing `north-icon-next` in the toggle button.

Please test out this feature before the next theme update. :)

### CODE REVIEW

**Comment by Misplon** [comment]
These are looking great, love the animation. Is there any chance we could align the down angle, either align middle or baseline with the link text. At the moment, it looks to be aligned top.

**Comment by adiraomj** [comment]
I positioned the button to appear in the middle(vertically) in the list item.

**Comment by Misplon** [comment]
Thanks :) The initial alignment is now correct. Unfortunately, this has negatively impacted the alignment of the close angle. Any chance we could sort that out, then, I think we're 100% with this great new addition.

toggle

**Comment by adiraomj** [comment]
Fixed all issue. 👍

**Pull request merged**
