### PR TITLE
Woocommerce cart

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #3 

Modified the default WooCommerce cart widget.
Added the cart icon to the header.
Added scss and compiled css.
Added function to dynamically update product count in header.

### CODE REVIEW

**Comment by gregpriday** [comment]
Very good work on this. It looks awesome. Glad to see you used the burst animation for the cart dropdown.

So the only thing I'd like to see in this is an option for the user to disable the cart in the menu.

We have 2 options here. We could either have the setting in the navigation section or we could create a new WooCommerce section. The extra WooCommerce section would be great if we plan on adding more WooCommerce related settings in the future. Which do you think is better?

**Comment by adiraomj** [comment]
I feel that an additional WooCommerce section would be better. It would be easier for a user to navigate the settings.

**Comment by gregpriday** [comment]
Prefect, lets go with a dedicated WooCommerce section.

**Comment by gregpriday** [comment]
Awesome stuff!

**Pull request merged**
