### PR TITLE
wishlist

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented Enhancement #71 

Added compatibility with [YITH wishlist](https://wordpress.org/plugins/yith-woocommerce-wishlist/) plugin.

Added wishlist icon.
Added Icon to products in loops.
Added wishlist link to product posts.
Styled wishlist page.

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Hopefully, there isn't a problem with my local setup, if there, perhaps you can lend a hand. I'm seeing the wishlist link added twice to the single product page. On the product archive page and the single product page, I'm missing the icon.

single-product

product-archive

**Comment by Misplon** [comment]
@adiraomj Repeating our Skype chat here so I have it logged. If possible, can you advise a way of closing this PR but still storing this work for future reference. Thanks :)

**Comment by Misplon** [comment]
@adiraomj Can you perhaps just keep this branch on your local machine? We can then delete this PR and when @braamgenis is able to work on the wishlist addon he can request the branch be pulled.

**Comment by adiraomj** [comment]
Yeah.. that's fine.. 👍

**Pull request closed without merging**
