### PR TITLE
Current menu item indication

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #77

### CODE REVIEW

**Comment by Misplon** [comment]
Guys, I haven't seen this done before but do you think we can expand the current menu indication to include one-page sites built with North? We wouldn't have the WP current menu item class to rely on, we'd perhaps need to match up the anchor link in the URL to the link text to see if it matches and then dynamically assign a class if it does. Any ideas? @gregpriday @adiraomj

**Comment by Misplon** [comment]
And, if we can achieve the above, could we look at integrating a position offset for anchor links? In summary, one-page websites need to offset their anchor positions by the given height of the sticky header. This plugin does this: https://wordpress.org/plugins/hash-link-scroll-offset/. But, I was thinking we could do it automatically. If sticky menu is on, and if an anchor link is being scrolled to, measure the header and offset the anchor scroll position. Possible @gregpriday.

**Comment by adiraomj** [comment]
@Misplon, I will explore ways in which we can use the current menu indication for single page menus. Great idea! 

As for the offset issue: To test out how the theme works by default I did the following.
1. Added a new page.
2. Added the prebuilt **We love design** layout to the page.
3. Added a ID's to the row's with services and work.
4. Created a menu with links to the different row's.
After this the rows seem to align themselves just fine below the sticky menu, without the need for an offset. I also works fine with the **Overlap Content** page option.

@gregpriday: With the above setup, I did notice that the row's did get get an outline when their links were clicked. I guess this may not be the most desirable for users. How about using `outline: none` for `.panel-grid` ?

**Comment by Misplon** [comment]
@adiraomj I provided custom CSS for a user to remove the outline for `.panel-grid` to remove the outline so definitely +1 from my side for that addition.

**Comment by Misplon** [comment]
@adiraomj, sorry man. Thanks for confirming the anchor overlap isn't an issue. I was mistaken, the overlap was occurring when an anchor link was clicked on from the mobile menu. Our updated mobile menu that closes when a link is clicked on should resolve this challenge nicely.

**Pull request merged**
