### PR TITLE
Fixed bug with large logo

### PR DESCRIPTION
**Pull request by adiraomj**
Fixed bug #161 

@AlexGStapleton can you please confirm that this solves the problem.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
It doesn't happen anymore but it doesn't really look good.


Could we set the logo to height: auto; on mobile? That way the logo won't extend the page width and it won't look so squished..

**Comment by Misplon** [comment]
@AlexGStapleton It's looking ok my side. Can you please, send me your tester logo. So I can have a go with that image? I threw a big one in there now 1080 x 420 and it looked decent.

**Comment by AlexGStapleton** [comment]
It's the same tester image included with the initial issue. It's dimensions are 485x66.

**Comment by Misplon** [comment]
@adiraomj At certain break points the logo isn't proportionally resizing, only the width is changing. Can we perhaps take a look at that? Thanks :)

logo

**Comment by Misplon** [comment]
@adiraomj Just one more small adjustment needed here I think.

**Comment by gregpriday** [comment]
@adiraomj @Misplon - this might be a fix for the logo sizing issue https://github.com/siteorigin/siteorigin-north/tree/pr/logoFix - last commit is just a small adjustment to how the scaling works.

**Pull request merged**
