### PR TITLE
Added option to disable smooth scroll on mobile

### PR DESCRIPTION
**Pull request by Misplon**
This is the same body class option we have in Corp.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
This isn't working for me - I'm not seeing any differences after using this. Where is `mobile-header-ns` coming from? I can't seem to find any references to it.

**Comment by Misplon** [comment]
You'd need to add the class if you wanted to disable sticky on mobile.

```if ( ! function_exists( 'siteorigin_north_child_body_classes' ) ) :
function siteorigin_north_child_body_classes( $classes ) {
	$classes[] = 'mobile-header-ns';
	return $classes;
}
endif;
add_filter( 'body_class', 'siteorigin_north_child_body_classes' );```

**Comment by Misplon** [comment]
This perhaps could also be done with a Body Class plugin, which one do you normally recommend?

https://wordpress.org/plugins/search/custom+body+classes/

**Comment by AlexGStapleton** [comment]
I would use the first plugin on that list:

https://wordpress.org/plugins/wp-custom-body-class/

I've used and recommended it in the past. I've never had an issue with it.

**Pull request merged**
