### PR TITLE
Added page featured image

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #154

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Thanks, looking awesome. Sorry, I forgot to ask. Please, can we implement with Page Template Settings in the Customizer.

**Comment by Misplon** [comment]
@adiraomj Sorry, my last post makes no sense. No page featured images on archive pages. 

Do you think we should introduce a post featured image setting into the Customizer Page Template Settings for archives?

**Comment by adiraomj** [comment]
We already have that setting.

Customizer -> Theme Settings -> Blog

**Comment by Misplon** [comment]
Indeed. I was just wondering if we should offer it on an archive by archive basis. But, thinking about it now. It could be too much. Let's rather see if there are any requests.

Thanks dude.

**Pull request merged**
