### PR TITLE
Menu allow hover when touch enabled

### LINKED ISSUE #356: Sub menu doesn't open on hover when browser has Touch Events API enabled
[Reported here](https://siteorigin.com/thread/submenu-hover-not-working-in-chrome/)

Appears to be related to [this section in north.js](https://github.com/siteorigin/siteorigin-north/blob/1.6.7/js/north.js#L115-L146).

Possible related PRs:
https://github.com/siteorigin/siteorigin-north/pull/97
https://github.com/siteorigin/siteorigin-north/pull/135

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolves #356

### CODE REVIEW

**Comment by Misplon** [comment]
The second tap on mobile doesn't open the parent link. To recreate, set your responsive breakpoint for the menu to `0`. Setup a parent with sub-menu items. Make sure the parent menu item is a page, not a link. The first tap on mobile should open the drop-down, the second should let me go to the page.

The issue is not present in the mobile menu.

This issue is not present in the develop branch.

**Comment by AlexGStapleton** [comment]
How does that look?  I've re-introduced the .hover check and restructured it to prevent issues with other submenus potentially popping up.

**Comment by Misplon** [comment]
The parent of the sub-menu only works as a tap on the third-tap on mobile. If I switch back to develop it works on the second tap.

**Comment by AlexGStapleton** [comment]
I can't seem to replicate that. Can you please try [this build](https://drive.google.com/a/siteorigin.com/uc?id=15PL0d40Rfv5KtNyInGWsTUa3E1Fauc0v)? This build works without issue for me so I just want to confirm if it's happening for you or not.

**Comment by AlexGStapleton** [comment]
How does that look? The menu is working for me while using Safari and the menu is working as intended when the Touch Events API is enabled.

**Comment by Misplon** [comment]
Looking good. Only challenge I can see is that it isn't possible to single tap open sub sub menus. Is that intentional?

**Comment by AlexGStapleton** [comment]
That's not intentional, and it's happening due to the same reasons as the other Safari issue. :(

How does that last commit look? I had to revert my last comment due to [this browser "feature"](https://www.chromestatus.com/features/5093566007214080) where the browser would sometimes simply not let e.preventDefault() because of an intentional technical limitation.

**Comment by Misplon** [comment]
With the latest change, in Chrome with Touch Events API enabled, you have to click to see a drop-down, hover doesn't work. In Safari, click doesn't show hover so there is no way to see the drop-down.

Everything works in Chrome and Safari on iOS.

**Comment by AlexGStapleton** [comment]
How does that look?

**Pull request merged**
