### PR TITLE
Masthead Fixes

### PR DESCRIPTION
**Pull request by adiraomj**
Fixed bugs #237 and #235

### CODE REVIEW

**Comment by Misplon** [comment]
Looking good :) 

Can we also look at fixing the page jump for logged in users?

**Comment by Misplon** [comment]
Menu issues seems to be resolved, looking good there.

**Comment by adiraomj** [comment]
Do you mean the page jump is still there when you have the admin bar present? I'm not seeing that issue.

**Comment by Misplon** [comment]
@adiraomj Are you testing with the top bar removed? It only seems to happen logged, with admin bar, without top bar text.

**Comment by Misplon** [comment]
Video: https://www.dropbox.com/s/aryagdt2foxp6ly/sentinel-logged-in.mp4?dl=0

**Comment by Misplon** [comment]
**Scroll Bar**
It looks overflow is adding a second scroll bar. Are you also seeing that?

overflow

**Comment by adiraomj** [comment]
@Misplon I'll check out the points that you have brought up tonight. 

As for the scrollbar. Check this out https://github.com/siteorigin/siteorigin-north/issues/63#issuecomment-197173211

**Comment by Misplon** [comment]
@adiraomj Awesome :)

There is a case for users applying the mobile menu on desktops, like what was done in Influence for example. Are there any ways around this? How do other menus handle this problem?

**Comment by Misplon** [comment]
@adiraomj If you have an opening this week, perhaps we can jump in here again. Thanks :)

**Pull request merged**
