### PR TITLE
Post formats

### PR DESCRIPTION
**Pull request by adiraomj**
Implement enhancement #168 

Added gallery format to functions.php.
Added templates for video and gallery posts.
Added flexslider css and js. ( loads only on gallery format posts )

@Misplon I have implemented this only for single posts. 
Do you think we should add settings for these? Similar to how we have a setting to display featured images.
Do you think we should also include a template for image format? Like we did for unwind?

### CODE REVIEW

**Comment by Misplon** [comment]
Awesome! I think these should also take effect for archive pages, as we did with Unwind. I don't think we need settings. I realise we're making a change late but choosing the post format is the setting in my mind.

**Comment by adiraomj** [comment]
Made changes. Please check.
What about image format?

**Comment by Misplon** [comment]
Super, thanks. Let's do Image too, the first image would just behave like a normal featured image would, unless you have another idea?

**Comment by Misplon** [comment]
**Gallery:** I'm keen to rather go with the default FlexSlider navigation and left/right arrows. Let me know your thoughts.

**Other:**
Let's do the same thing with Audio and Image, place those items in the position the featured image would usually be in. Let me know if you have any other ideas. Thanks :)

**Comment by adiraomj** [comment]
Everything sounds good.

**Comment by Misplon** [comment]
Awesome! Looking great. Do you want to consider using the normal Flex Slider arrows rather than the Unwind arrows?

**Pull request merged**
