### PR TITLE
Improve siteorigin_north_menu_breakpoint_css

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Follow up PR to #231 based on Greg's comments.

I also removed the repeated CSS as there's no real reason for it as far as I can tell.

### CODE REVIEW

**Comment by gregpriday** [comment]
Aaah yeah, this is much neater. So I actually checked [isset](http://php.net/manual/en/function.isset.php), and it checks for existing and non-null. So this is exactly what we'd be looking for (instead of is_null, which I'm not sure handles non-existant).

**Comment by gregpriday** [comment]
One more thing that I missed. It wouldn't be a bad idea to wrap `$breakpoint` with intval. Just to make sure nothing strange is getting injected.

**Comment by AlexGStapleton** [comment]
Are you suggesting that `$breakpoint` should be wrapped in both instances, or when it's set? If the latter, would you prefer:

`$breakpoint = isset( $settings[ 'theme_settings_responsive_menu_breakpoint' ] ) ? intval( $settings[ 'theme_settings_responsive_menu_breakpoint' ] ) : 600;`

Or:

`$breakpoint = intval( isset( $settings[ 'theme_settings_responsive_menu_breakpoint' ] ) ? $settings[ 'theme_settings_responsive_menu_breakpoint' ] : 600 );`

The former makes slightly more sense imo but I just want to confirm before I proceed.

**Comment by gregpriday** [comment]
`$css .= '@media screen and (max-width: ' . intval( $breakpoint )  . 'px) {` would make the mose sense to me.

**Pull request merged**
